# Generated by Django 2.2.2 on 2019-06-15 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address_full_address', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_lng', models.FloatField(null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size_in_bytes', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('FAILED', 'Upload Failed'), ('ADDED', 'File Added'), ('PROCESSING', 'Digitization In Progress'), ('DIG_FAILED', 'Digitization Failed'), ('DIGITIZED', 'Digitized')], max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address_full_address', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_lng', models.FloatField(null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('last_unit_price', models.FloatField()),
                ('unit_of_measure', models.CharField(blank=True, max_length=20, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Vendor')),
            ],
            options={
                'unique_together': {('item_id', 'vendor')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('CREDIT', 'Credit Card'), ('DEBIT', 'Debit Card')], max_length=20, null=True)),
                ('sub_total', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('paid', models.FloatField(blank=True, null=True)),
                ('refund', models.FloatField(blank=True, null=True)),
                ('due', models.FloatField(blank=True, null=True)),
                ('state', models.CharField(choices=[('FILE_ADDED', 'File Added'), ('IN_PROGRESS', 'Digitization In Progress'), ('PARTIAL_DIGITIZED', 'Under Review'), ('DIGITIZED', 'Uploaded')], max_length=20)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.Buyer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.File')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoice.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('serial_no', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.VendorItem')),
            ],
            options={
                'ordering': ('serial_no',),
                'unique_together': {('invoice', 'serial_no')},
            },
        ),
    ]
