# Generated by Django 2.2.2 on 2019-06-15 09:04

from django.db import migrations, models
import django.db.models.deletion
import invoice.models.file
import invoice.models.invoice
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address_full_address', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_lng', models.FloatField(null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_object_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('size_in_bytes', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[(invoice.models.file.FileState('Upload Failed'), 'Upload Failed'), (invoice.models.file.FileState('File Added'), 'File Added'), (invoice.models.file.FileState('Digitization In Progress'), 'Digitization In Progress'), (invoice.models.file.FileState('Digitization Failed'), 'Digitization Failed'), (invoice.models.file.FileState('Digitized'), 'Digitized')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('state', models.CharField(choices=[(invoice.models.invoice.InvoiceState('File Added'), 'File Added'), (invoice.models.invoice.InvoiceState('Digitization In Progress'), 'Digitization In Progress'), (invoice.models.invoice.InvoiceState('Under Review'), 'Under Review'), (invoice.models.invoice.InvoiceState('Uploaded'), 'Uploaded')], max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Buyer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.File')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address_full_address', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
                ('geo_location_lat', models.FloatField(null=True)),
                ('geo_location_lng', models.FloatField(null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('last_unit_price', models.FloatField()),
                ('unit_of_measure', models.CharField(max_length=20, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('unit_price', models.FloatField()),
                ('serial_no', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.VendorItem')),
            ],
            options={
                'ordering': ('serial_no',),
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Vendor'),
        ),
    ]
