# Generated by Django 2.2.2 on 2019-06-15 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ('invoice', 'serial_no')},
        ),
    ]
